import Head from 'next/head'
import { Provider } from 'react-redux'
import { useStore } from '../store'
import CssBaseline from '@mui/material/CssBaseline';


export default function App({ Component, pageProps }) {
  const store = useStore(pageProps.initialReduxState)

  return (
    <Provider store={store}>
      <CssBaseline />
      <Head>
        <title>Farm Database</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/solita.png" />
      </Head>
      <Component {...pageProps} />
    </Provider>
  )
}